# Generated by Django 4.1.1 on 2022-09-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
