# Generated by Django 4.1.1 on 2022-09-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mailid', models.EmailField(max_length=30)),
                ('mobile', models.IntegerField(max_length=10)),
                ('address', models.TextField(max_length=100)),
                ('registration_number', models.IntegerField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('make_of_vehicle', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('year', models.IntegerField(max_length=30)),
                ('current_mileage', models.CharField(max_length=30)),
                ('dealer_name', models.CharField(max_length=30)),
            ],
        ),
    ]
