# Generated by Django 4.0 on 2022-10-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnqInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=10)),
                ('travel_destination', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('no_of_person', models.IntegerField()),
                ('vacation_type', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'enquireform',
            },
        ),
    ]
