name=input("enter employee's name:")
hw=int(input("enter no. of hours worked in a week:"))
hp=int((input("enter hourly pay rate:")))
ft=int((input("enter federal tax withholding rate:$")))
ded=int(input("Enter deduction:$ ")) 
st=int((input("enter state tax withholding rate:")))
totded=int(input("Enter Total deduction:$ "))
np=int(input("Enter netpay=$ "))
print("Employee's Name=",format(name))
print("Hours Worked={}",format(hw))
print("Pay Rate={}".format(hp))
print("Gross Pay={}".format(ft))
print("Deduction:Federal withholding={}".format(ded))
print("State with holding={}".format(st))
print("Total Deduction={}".format(totded))
print("Net pay={}".format(np))
